FROM zabbix/zabbix-server-mysql:ubuntu-latest

USER root

RUN apt update && \
  apt install -y --no-install-recommends curl zip gnupg libaio-dev && \
  wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basic-linux.x64-21.9.0.0.0dbru.zip && \
  wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-odbc-linux.x64-21.9.0.0.0dbru.zip && \
  unzip instantclient-basic-linux.x64-21.9.0.0.0dbru.zip -d /usr/lib && \
  unzip instantclient-odbc-linux.x64-21.9.0.0.0dbru.zip -d /usr/lib && \
  rm -rf instantclient-basic-linux.x64-21.9.0.0.0dbru.zip && \
  rm -rf instantclient-odbc-linux.x64-21.9.0.0.0dbru.zip && \
  mv /usr/lib/instantclient_21_9 /usr/lib/oracle && \
  ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/oracle/libaio.so.1 && \
  echo /usr/lib/oracle/ > /etc/ld.so.conf.d/oracle.conf && \
  ldconfig && \
  curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
  dpkg -i packages-microsoft-prod.deb && \
  apt update && \
  ACCEPT_EULA=Y apt install -y msodbcsql18 && \
  rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/usr/lib/oracle"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib/oracle"
