FROM zabbix/zabbix-web-nginx-mysql:ubuntu-latest

# USER root

# RUN sed -i 's/5050072/6010003/g' /usr/share/zabbix/include/defines.inc.php

USER 1997

COPY msyh.ttf /usr/share/zabbix/assets/fonts/DejaVuSans.ttf
