FROM zabbix/zabbix-web-nginx-mysql:ubuntu-trunk

# USER root

# RUN sed -i 's/5050072/5050068/g' /usr/share/zabbix/include/defines.inc.php

USER 1997

COPY msyh.ttf /usr/share/zabbix/assets/fonts/DejaVuSans.ttf