FROM zabbix/zabbix-server-mysql:ol-latest

USER root

RUN microdnf install yum && \
  microdnf install oracle-instantclient-release-el8 && \
  microdnf install oracle-instantclient-basic && \
  microdnf install oracle-instantclient-odbc && \
  curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo && \
  ACCEPT_EULA=Y yum install -y msodbcsql18 && \
  yum clean all

ENV PATH="${PATH}:/usr/lib/oracle/21/client64/bin"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib/oracle/21/client64/lib"
ENV OPENSSL_CONF="/var/lib/zabbix/.openssl_allow_tls1.0.cnf"
ENV ORACLE_DIRVER="/usr/lib/oracle/21/client64/lib/libsqora.so.21.1"

RUN printf "openssl_conf = openssl_init\n\n[openssl_init]\nssl_conf = ssl_sect\n\n[ssl_sect]\nsystem_default = system_default_sect\n\n[system_default_sect]\nCipherString = DEFAULT@SECLEVEL=1" > ~/.openssl_allow_tls1.0.cnf
